### ISSUE TITLE
Cannot submit a report after cancel page if the victim use "<-" to go to previous page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1600]
## Summary

Cannot submit a report after cancel page if the victim use "<-" to go to previous pages instead of click on "Create a new report"

## Steps to reproduce
1. Launch report and fill out the form
2.  At summary page, the user wants to cancel the report
3. After cancel report, the user wants to fill out the report again but he/she uses "<-" key to get back to summary page and edit each session to enter information instead of click on "Create a new report" option 
4. The user receives the message "Submitting your report ..." at the Thank you page and after 2 minutes, the user receive an message "Sorry, your report was not successfully submitted"

Here is my concern
1. Currently, we allow the user to submit their report again if they use "<-" key but it does not work if the user cancels their report and want to submit it again with "<-" key
2. Why does it take so long (2 min) to receive an error message

![thankYou](https://user-images.githubusercontent.com/60269104/75567436-87612c80-5a1f-11ea-93d4-bdabfaf16cdb.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sastels** [comment]
I think that issue #1602 will fix this.

**Comment by lmcbhvu** [comment]
I retest it  and I still get the same error. Need to take a look again

**Comment by sastels** [comment]
Ah, I thought this was a duplicate of the "go back after submitting" issue - I hadn't realized that this was "go back after cancel".

Currently if a user does this then the confirmation page will crash with a `TypeError: "n.formData.anonymous is undefined"` error (because we've deleted all their data from state). Probably not the behaviour we want. We probably want to go back to one of the original ideas that if a user gets to a page and consent isn't checked then we bounce them back to the consent page.

**Comment by amazingphilippe** [comment]
Is this still broken after last week's #1872 ?

**Comment by lmcbhvu** [comment]
This issue will be closed because as it said in #1925,  the user has to report again after canceled the report
