### ISSUE TITLE
Should we have a session time out on the report?

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1608]
## Summary

Should we have a session time out on the report?

## Design Detail

> Explain the design in enough detail for somebody familiar with the infrastructure to understand. This should get into specifics and corner-cases, and include examples of how the service is used. Any new terminology should be defined here.

> Include an image of any old vs new design changes if possible

> include links to figma or other design designs if possible

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by stephaniemgauthier** [comment]
I think it's a good idea but we'll need to inform the user at the beginning. They'll need to gather all supporting documentation first. Also need to anticipate fewer beta reports coming in with a time out.

**Comment by sastels** [comment]
In general with a more traditional server-rendered app you need a session timeout just so that the server didn't run out of memory holding onto people's partially completed reports (in particular when the user has left and is not coming back).

Our app runs entirely on the client side so our server does not hold temporary data, thus there are no technical problems that having a timeout solves.

**Comment by lmcbhvu** [comment]
Based on Steve's note, no session time out is required for our app. This issue will be closed
