### ISSUE TITLE
Should an error message be removed if the user enters the valid postal code

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1700]
## Summary

Error message should be removed if the user enters the valid postal code

## Steps to reproduce
Go to location page
Enter invalid postal code 123456 -> Error message is displayed
Enter the correct postal code --> Error message is still displayed

![postalCode](https://user-images.githubusercontent.com/60269104/77081391-f7385680-69d0-11ea-97b8-702bf8574979.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by amazingphilippe** [comment]
Just wanted to add some context to help make a decision:

We want to limit changes on a page to a minimum. This helps users that are slower, and that can be disoriented by elements disappearing from the page as they type something in an input. That's why we only update validation once the user clicks on 'continue' : if there's no errors, we go to the next page, if there are still errors, we stay on the page and the error message remains.

It's advised to: 

>Do not validate when the user moves away from a field. Wait until they try to move to the next part of the service - usually by clicking the ‘continue’ or ‘submit’ button at the bottom of the page.

[source](https://design-system.service.gov.uk/patterns/validation/#when-to-tell-the-user-about-validation-errors)

**Comment by lmcbhvu** [comment]
The first time, the error message is not displayed. When the user enters the wrong postal code, the error is appeared. It is good. The user corrects the postal code and hit continue. It is correct format, it will move to the next page, else it stays at the same page and force the user reenters postal code. I think it is ok. But if the user wants to edit and change the postal code, do we suppose to see that error message when he clicks on the edit button and come back on the location page? It is little bit of confusion to the user

**Comment by sastels** [comment]
It seems that there's no way to actually enter a postal code - all values fail validation.

**Comment by DianeLiu2019** [comment]
close the issue . the designer change to "add an error message below the postal code label" see issue #1745
