### ISSUE TITLE
Consistency for translations

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/report-a-cybercrime#1729]
## Summary

We use different methods for translating content in components and in general

- We use Trans tags as jsx
- We use Trans tags in jsx properties
- We use the i18n._() function
- We pass lingui ids through jsx properties:
  - to use in Trans tags
  - to use in 18n._() functions
- maybe more?

## Motivation

To make things easier to understand, maintain and document, could we choose a few consistent ways to translate content? Especially focusing on flexibility.

Another motivation would be to reduce the need for marking lingui ids in empty react fragments.

**Comment by sastels** [comment]
I think we should use `<Trans>` tags whenever possible (in particular, as it allows lingui to mark those keys and we don't have to do it manually with those `{false ...}` blocks). In particular, passing a `<Trans/>` block as a prop rather than passing the key and doing the `<Trans>` in the subcomponent. An added benefit is that the subcomponent is simpler to write because it doesn't need to use lingui.

There are some places we can't use trans though, for example aria-label tags (and, in general, tags to basic html elements). Here we should use the `i18n._()` and mark those keys with a `{false...}` block so that then are recognized by lingui.

I suggest as a first step we go a search for `i18n._` and replace any that we can.

**Comment by ngosset** [comment]
Looks like the PR was closed and deemed unnecessary, but the issue was left open. Closing for now.
