### ISSUE TITLE
"Add suspect clues" page should follow the same flow as other pages when the user cancels the report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1924]
## Summary

"Add suspect clues" page should follow the same flow as the other pages when the user cancels the report. 
As the fix in PR#1908,  if the user cancels the report in the middle way and use the back arrow key to go back to the previous pages, it will take the user to the your privacy page.

At Add suspect clues page, it will take the user to Add suspect clues instead of your Privacy page after the user cancels the report and uses back arrow key to go back. It will take a user to privacy page when the user presses Continue 

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sdzhangtao** [comment]
Can you give me the steps to reproduce? I am a bit confused by reading your descriptions.
Can you explain the following a bit more.
"At Add suspect clues page, it will take the user to Add suspect clues instead of your Privacy page after the user cancels the report and uses back arrow key to go back. It will take a user to privacy page when the user presses Continue"

**Comment by lmcbhvu** [comment]
@sdzhangtao Here is the steps
1. Launch the report and process to go to Add suspect clues page
2. Press "cancel" at Add suspect clues page
3. Press back arrow twice
Expected result: It should be go back to your privacy page (like when you cancel at the other pages) 
Actual Result: It goes back to Add suspect clues page
