### ISSUE TITLE
Refresh/reload the fyi flow will take the user back to full report flow

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2181]
## Summary

The user starts the report with fyi flow. At middle of report, they reload or refresh the page, it will take them to the full report instead of short report (fyi ) flow

## Steps to reproduce

1. Submit the short form (fyi flow)
2. Stop at what happened page (Tell us about the scam or computer crime page)
3. Refresh or reload the page
4. It will go back to "Your privacy" page
5. Accept the term and press continue

Actual Result: It goes back to full report flow
Expected Result: It should go back to short report (fyi) flow

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by lmcbhvu** [comment]
When the page is reloaded, it will go back to the privacy page of FYI, not full report

**Comment by ngosset** [comment]
We've had this since day 1 unfortunately. Expected behaviour with the chosen architecture. Because the state remains client side until the user hits the final page. The solution is to start tracking some state server side, or persist some state to something that survives page requests (HTML5 storage? Something else?)

I would like to fix this eventually.
