### ISSUE TITLE
Multiple Scans on Single File

### ISSUE THREAD

**Issue by justinr86** [cds-snc/report-a-cybercrime#2285]
## Summary

When an image is uploaded the file seems to be scanned twice - once as a jpg and once as a png. This seems to be unnecessary and could cause performance issues when the application is scaled up. See screenshot below:

![duplicate](https://user-images.githubusercontent.com/62246403/93244257-7081ed80-f757-11ea-8197-c3a9dbdefe93.png)

This may not be an issue, but if it is this should be investigated.

## Steps to reproduce

1. Create a report

1. Upload a PNG

1. View server log after submission

## Unresolved questions

Is there a reason both the original and converted file are scanned and upload?

**Comment by ying-chen-cds** [comment]
The image is only scanned once. After scanning, png file is converted to jpg file. Then both files are encrypted and upload. The log (first section) captured in the screen is more likely for debugging purpose. We can remove it if feel confused. Otherwise, we can just close the issue. I leave this open to the team.
