### ISSUE TITLE
Cosmetic bug: Should we add more space between options in What were affected page?

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2288]
## Summary

When the page is minimized, there is no space between Business and Other options (please see the below picture).  

![image](https://user-images.githubusercontent.com/60269104/93262092-a6cc6680-f771-11ea-9597-105ce8138ea0.png)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by sdzhangtao** [comment]
Hi Justin,

This issue only happens when the browser screen is medium. We might need more responsive css.

**Comment by ying-chen-cds** [comment]
Yes, I think we need it to be more responsive. It is not only happening to this page, it's happening to other pages too (e.g. Mid-feedback page). Actually, you don't have to make browser screen smaller to see this problem, as long as you put a long text for the checkbox/radio, you'll see it. It seems that the reason is we used fix height(2.5rem) for checkbox/radio, so they lose the responsiveness. I see that when we set the height to 2.5rem, the space between the checkbox/radio is a bit larger, but I don't think that's worth the tradeoff of losing responsiveness.
