### ISSUE TITLE
Duplicate info is displayed on analyst email when it is changed from anonymous to non-anonymous report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2293]
## Summary

When the report is changed from anonymous to non-anonymous, the duplicate info (city and province)  is displayed. Should we display the same format for non-anonymous report (Postal code, City from postal code and Province from postal code are displayed).

Currently, the City or municipal, Province, postal code, city from postal code and province from postal code are displayed in the analyst email.

![image](https://user-images.githubusercontent.com/60269104/93523823-9a771380-f901-11ea-8e1b-ce11459119a6.png)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by ying-chen-cds** [comment]
This is caused by data is not cleared when changing anonymous settings. When it is anonymous, the location page would ask you to enter City or municipal, Province; when it is not anonymous, the location page asks you to enter postal code. The problem is when user changes anonymous from yes to no, City or municipal, Province should be cleared but it's not. And vise versa (i.e., when user changes anonymous from no to yes, postal code should be cleared). We can see this in the confirmation page.
![location](https://user-images.githubusercontent.com/68352206/93622474-36a92500-f9ab-11ea-9056-b1a377f370ef.png)
In stead of only showing City or municipal, Province if anonymous is yes, and only showing postal code if anonymous is no, it shows all three fields. Once this is solved, the duplication in the analyst email will be gone automatically(if there is no postal code, city from postal code and province from postal code won't show).

**Comment by lmcbhvu** [comment]
Yes, I agree. We should have the same info as non-anonymous report (Location with postal code only)
