### ISSUE TITLE
Should not leave blank after "and" word at summary page 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2372]
## Summary

If the user clicks all or some options before or after Other option in  "How were your money or finances affected?" page, and don't put anything in the text area of  other option. At summary page, it should not leave blank before and after "and" word at summary page.
Currently, it shows  "Method of Payment: E-transfer, Credit card, Gift card, Cryptocurrency, and " 
or "Method of Payment:     and Cryptocurrency

![image](https://user-images.githubusercontent.com/60269104/96188823-65b0a900-0f0d-11eb-9d36-26d6b7db0ae7.png)

![image](https://user-images.githubusercontent.com/60269104/96189405-6c8beb80-0f0e-11eb-8645-df55f6e89a43.png)

## Steps to reproduce

1. Submit a report
2. At page "How were your money or finances affected?", click all options but don't put anything in other text area OR click other option first and then the other options
3. Complete the report until reach to summary page

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by dengcn** [comment]
This is a bug. it needs to get input from business team, If user clicked "Other", but did not type in anything in the input field, 
should we just remove ", and" in the summary/report or something else?

**Comment by dengcn** [comment]
Hong,  here is how I fixed and implemented.  

1) If clicked "Other", and have value in,  like ："House" in "Other" Field. the summary looks like this:### 
XXXX, XXX, XXXXX and House

![DemoPage_ClickedOtherAndHaveHouseFilled](https://user-images.githubusercontent.com/5130380/96513551-41680b80-1230-11eb-96e6-66da40b3b0e3.jpg)

2) If clicked "Other", and have no value filled in, and Others will be shown, since we need to reflect user clicked "Other"
it looks like this
![DemoPage_ClickedOtherButNotValueFilled](https://user-images.githubusercontent.com/5130380/96513665-73796d80-1230-11eb-8909-b7989eafc2f8.jpg)


Let me know if above are acceptable, thanks

**Comment by lmcbhvu** [comment]
I agree with your solution
